dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- python -m tree_stat sample-tree --pov parent -o actual-travis-stat.md # test script against sample data
- diff actual-travis-stat.md tests/assets/expected-tree-stat.md # compare sample result with expected result
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  on:
    tags: true
    python: 3.7
  password: ${PYPI_PASSWORD}
