dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- cd tests/assets
- python -m tree_stat sample-tree -o travis-stat.md # test script against sample data
- diff travis-stat.md sample-tree-stat.md # compare sample result with expected result
- cd ../..
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  server: https://test.pypi.org/legacy/
  on:
    tags: true
  password:
    secure: Ua1hbnJMtVW8TtEG+WJGlJVMqOssk2oxtkLQctJTgDPgISdnXn7yC9GoYIdP5myH6vaHIRwBWP4IfMyJO7e5ZpHJ6WQ7F0uHhZKoB5Qj+OA5mdju6KUmCoH+29YIaCJyMNxVt69+DvQ+CS74eenVQsfxPiOaVEpVLfhVNfnvMX82KJ5NmcigLVjrzpq1OThqtAmsuzA539HfOqITkhoo6dXBejUooFwXtpEUDyWwnD5tfiaMhA+qnqe3kD51b5L+MJOlRAS1DMuVMYmw5rxI26ztA5xr2ho/1jMHx/LRFGr7nKj4jYh7ogXY+YuygkfoWUfK6kGnCOB9f7DZVP+NTBmawIK9b+akgHw99gmx5qnbEWNsrEt5oYV8wjz1BYgZLIMdCcZKDNutNtX/GfTELs4EFjjOelfDD6LrtEGwkH/bfoZ6hs8uztxYJfGrKtLUk2ZTQWyUtc1EJvI1V+kxk05VsHBsEb492JyRz7ucv1j/UXf5GASMM6XIZyOAZ1CBA8KOAvux1Jt6ugSrqjM6fa3sR5mNYbNSmTFQPRzSmhQmlrZqbVqC7x8XFeUTZX2UQQKpNPNKrFDAfXIx9/Z9tOU/pcxHL/R+rJ92aC+iJTHbtnkg3txUFkG/buobH4XWwLw3yLSqW3rnzDfd3TscBfvBSLG4kn1+7AtCUPGarxc=
