dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- python -m tree_stat tests/assets/sample-tree -o actual-pov-None-tree-stat.md
- diff actual-pov-None-tree-stat.md tests/assets/pov-None-expected-tree-stat.md
- python -m tree_stat tests/assets/sample-tree --pov parent -o actual-pov-parent-tree-stat.md
- diff actual-pov-parent-tree-stat.md tests/assets/pov-parent-expected-tree-stat.md
- python -m tree_stat tests/assets/sample-tree --pov root -o actual-pov-root-tree-stat.md
- diff actual-pov-root-tree-stat.md tests/assets/pov-root-expected-tree-stat.md
- python -m tree_stat tests/assets/sample-tree --pov target -o actual-pov-target-tree-stat.md
- diff actual-pov-target-tree-stat.md tests/assets/pov-target-expected-tree-stat.md
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  on:
    tags: true
    python: 3.7
  password: ${PYPI_PASSWORD}
