dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- cd tests/assets
- python -m tree_stat sample-tree -o travis-stat.md # test script against sample data
- diff travis-stat.md sample-tree-stat.md # compare sample result with expected result
- cd ../..
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  server: https://test.pypi.org/legacy/
  on:
    tags: true
  password:
    secure: "SHS7ZJOv8DHWtwgL/duZZEDGej4FZkZ8B4p50xvm55XrN2CQEQAbKSe0arteSbPw5qUnpsEdqBzDDRbRS8oxgLu4Tc/hTA8X1fKGobPzSzNeMQthBpZBGbi9G5xEldE2FS8/pdIILP60dfgobLh/FTd/pkradfhQ0GBSnHoENhXxxfGR3U/40tq+VpGY96BjecjOJgoQfnl+EsB+qN9vaTATVtH5ORDyGBxZaAbJxWeEM/gNUti8LHl4UGMnu7ZIahPuGZH/Q6D17ozowIINE7Ek0USJaP+A14lZ8538a6LZKdD9quissExbVTR3wSXCQwLNi07zrgmOl6lbKmkOJJYo7dSSq4op5H9cGb2S3HnlcoSWEFE1D4truHSyNQxvWHPLOIHmRbQp1JmaHKBuqW0C8eLNxy9YVueuHBN/KQfJLNRJJ8X+gh3QrvoZomyT4OJ2+HBHZl7/nVwCyJ3Egbn4RT8BlcgOtrR7pQqYzmice7xXMXPs/GR5DYELgWiXk3aSUpANLWLKciqq/npPuzTO9E4xAreP6KEYSDkI11svibfM1fySUD2utISNJ9/MRJ7LFI+R76DbHmRXcmwnWTGojBemoYdX45lhOgXRWW3verM1B2PB8x0BY+M5gF9ueN4ax/YXpSYs5Jz/I3av4u7PEnZFG5Yxf6FyzIdPp5Y="
