dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- cd tests/assets
- python -m tree_stat sample-tree -o travis-stat.md # test script against sample data
- diff travis-stat.md sample-tree-stat.md # compare sample result with expected result
- cd ../..
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  server: https://test.pypi.org/legacy/
  on:
    tags: true
  password:
    secure: "aZ/lnIt8WIR7N9F6rCg3DDuxY4Tbod6W+QOXd0aDnN/25zowiakypciqYjXoX8Fz+ZhMwlT8rFAUpaeVyHbcL4YxJ941fV7xAA3njBwwDhz47KYCnYWKYwYZuQ3PCW3HUzQl/guZEPWk+4vXwkO2IH2o6iT7oI13JmtCKrw7j3mRQisHkPAp1Fd6XWvhCdkiMdBDa2ogQ44keUKnm2TgPBj6sWclA/LV9O8k1Emu2Xq4IMziopwCyBPbMhTsZr8ewa7zXhOpUiiKyuDAwWZjtsvXpy9SmSDEP8G0seBa643xUjRDlJARLFD/2Dad1m5trmcxAPSx2ZwrNb2KwEJWDPbMPTXWSxpLF8r/+p0oXhk9f0UWCqUpr2Ea1IV5T4HtjPfI0Zjep6P6TJSvUQ1F7vhjx83Bd1+celuSKPiuvR67scqae6+fJP+lYFmZ5kLL5lFN/XgliUhyJATGSHbbXN9+uL5gH899nOCkiuUApjKkC0bM3efbooPVz2aNnuUqYf2njQ3cwMvdfx/8gQ4C9uGYgABF7TKQLZs0Kum01301V+7aLLMjF3zBOJJ4/gyF8sYK0SpgT2C6LYp+Ye7JIyHPFw0HHvXXoPTHA15L9Li30mIGA/hjfraqVkv8MBqwocCTEw7pI08sKtic5kGH0qF++eBxakqqzYlZO2JlDmE="

