dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
cache: pip
before_install:
- pip install --upgrade pip # travis use an ancient version...
- pip install pip-tools # pip-tools to generate requirements.txt
- pip-compile # generate requirements.txt
before_script:
  - pip install -e .[dev] # install dev dependencies to test
script:
- python -m pytest # unit tests
- python setup.py build install # build and install so that I can test
- cd tests/assets
- python -m tree_stat sample-tree -o travis-stat.md # test script against sample data
- diff travis-stat.md sample-tree-stat.md # compare sample result with expected result
- cd ../..
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ahorgnies
  server: https://test.pypi.org/legacy/
  on:
    tags: true
  password:
    secure: Ke/jm7nGDO+FIsA2Uoy3YMomJo0WzGZ7NEZ4Bba/SpR3cs+JyDcR67FEiE7eT4ktTtMsZq8L/AOY7hJq+jotIBzd/GuJl/6jDX5/FE48hrFZmTFdml+ruwlciqijeVIWFznzNvbF2Drq2dYflkzwpiCzi9Mrro3TNzD9I/YxAkGC6MQSnIM4BEs8z724FRCOu5+6mgJE98W17t1LQD/7cPRitz4SE5geZ8uy5Bxp9LvIzOYCJR4g+QQrjshQcSKblXNaGRNltiAWn1+PQctA0CZRxPLE52ivEIjl7zAPXmMJeKeS7Mvz74h/98NBgKPrbZwjYLeTjsHxcUbgUVDoWdgla4wk5jjF10OVfRx2IvYIvygAMOY8HwcuYKpht9+cuJylIpik1lR+Df7OD1accuO3Q1YoRqaL36vyYtPGVz34mkCKMmCr9vIFVHolv5bc8jxEC9++u/bQsyC5rTvS5vqSN3+fRkfctJZYV9mrTrMUTv00RMyC1oVXd39Davi6HzRHRPf6DqbjcOL41+1l2shZ9pmFUbYkfIaOsIeixQBbiQPsVtd9YJYQp67kUcSvrymZQdUAryFo6K1OIBuJNKWkAx2j7+NERGIBaGiUGCZJ+lWbhq5vbhGi62lQIAUfJL/lolUIXgBk+83OiM3+KNpMqh91p4cc766O4KIC+2E=
